server:
  port: 8080
  servlet:
    context-path: "/api/v1"

spring:
  datasource:
    url: jdbc:h2:mem:users
    driverClassName: "org.h2.Driver"
    username: hadeoh
    password:
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: "/h2db"
